#!/usr/bin/env python3
"""Derive the Kafka topics actually referenced in code and cross-check them against
docs/messaging/kafka-topics.md.

Writes docs/messaging/kafka-topics.generated.md (do not hand-edit — see docs/GENERATED.md).
Exit 1 if a topic is used in code but not registered in the catalog.

Heuristic and deliberately simple: adjust PRODUCE_HINTS to your codebase's publishing style.
Usage: scripts/generate-topic-catalog.py [workspace-root]
"""
import os, re, sys

ROOT = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(ROOT, "docs/messaging/kafka-topics.generated.md")
CATALOG = os.path.join(ROOT, "docs/messaging/kafka-topics.md")

TOPIC = r'"([a-z][a-z0-9]*\.[a-z0-9-]+\.[a-z0-9-]+(?:\.v[0-9]+)?(?:\.(?:dlq|retry))?)"'
CONSUME_HINTS = [re.compile(r"@KafkaListener")]
PRODUCE_HINTS = [re.compile(r"\b(send|publish|append)\s*\("), re.compile(r"TOPIC[A-Z_]*\s*=")]
TOPIC_RE = re.compile(TOPIC)

# Pass 1: resolve `public static final String NAME = "topic";` into Class.NAME -> topic, so the
# conventional holder-class style (`send(LedgerTopics.ENTRY_POSTED, ...)`) is visible. The old
# heuristic only saw inline literals or constants literally named TOPIC*, which meant a
# well-structured codebase produced an empty catalogue and a green build.
CONST_DECL = re.compile(
    r'static\s+final\s+String\s+([A-Z][A-Z0-9_]*)\s*=\s*' + TOPIC)
consts = {}          # "Class.CONST" and "CONST" -> topic
uses_kafka = False
for dirpath, dirnames, files in os.walk(ROOT):
    dirnames[:] = [d for d in dirnames if d not in (".git", "target", "node_modules", ".claude")]
    for f in files:
        if not f.endswith((".java", ".kt")):
            continue
        text = open(os.path.join(dirpath, f), encoding="utf-8", errors="replace").read()
        if "@KafkaListener" in text or "KafkaTemplate" in text or "@RetryableTopic" in text:
            uses_kafka = True
        cls = os.path.splitext(f)[0]
        for name, topic in CONST_DECL.findall(text):
            consts[f"{cls}.{name}"] = topic
            consts.setdefault(name, topic)

CONST_REF = re.compile(r'\b((?:[A-Z][A-Za-z0-9]*\.)?[A-Z][A-Z0-9_]{2,})\b')

found = {}  # (topic, role) -> [locations]
for dirpath, dirnames, files in os.walk(ROOT):
    dirnames[:] = [d for d in dirnames if d not in (".git", "target", "node_modules", ".claude")]
    for f in files:
        if not f.endswith((".java", ".kt")):
            continue
        full = os.path.join(dirpath, f)
        rel = os.path.relpath(full, ROOT)
        for lineno, line in enumerate(open(full, encoding="utf-8", errors="replace"), 1):
            consuming = any(h.search(line) for h in CONSUME_HINTS)
            producing = any(h.search(line) for h in PRODUCE_HINTS)
            if not (consuming or producing):
                continue
            role = "consumes" if consuming else "produces"
            topics = list(TOPIC_RE.findall(line))
            # resolve constant references on the call site to their declared literal
            for ref in CONST_REF.findall(line):
                if ref in consts:
                    topics.append(consts[ref])
            for topic in set(topics):
                found.setdefault((topic, role), []).append(f"{rel}:{lineno}")

lines = ["# Kafka topics referenced in code",
         "",
         "> Generated by `scripts/generate-topic-catalog.py` — **do not edit** (see `docs/GENERATED.md`).",
         "> The hand-written catalog with owners, retention, and rationale is `kafka-topics.md`.",
         "",
         "| Topic | Role | Where |", "| --- | --- | --- |"]
for (topic, role), locs in sorted(found.items()):
    lines.append(f"| `{topic}` | {role} | " + ", ".join(f"`{l}`" for l in sorted(locs)) + " |")
if not found:
    lines.append("| _none found_ | | |")
open(OUT, "w", encoding="utf-8").write("\n".join(lines) + "\n")
print(f"wrote {os.path.relpath(OUT, ROOT)} ({len(found)} topic/role pairs)")

# A repo that clearly speaks Kafka but yields no topics means the heuristic missed — not that
# there is nothing to report. Failing here is the difference between a silent green build and a
# visible "adjust PRODUCE_HINTS" signal.
if uses_kafka and not found:
    print("::error:: this repo uses Kafka (@KafkaListener / KafkaTemplate / @RetryableTopic) but "
          "no topics were resolved — the extraction heuristic missed. Check TOPIC / PRODUCE_HINTS "
          "against this codebase's publishing style before trusting a green build.")
    sys.exit(1)

catalog_text = open(CATALOG, encoding="utf-8").read()
in_code = {t for (t, _) in found}
registered = set(re.findall(
    r"`([a-z][a-z0-9]*\.[a-z0-9-]+\.[a-z0-9-]+(?:\.v[0-9]+)?(?:\.(?:dlq|retry))?)`", catalog_text))

fail = 0
for t in sorted(in_code - registered):
    print(f"::error:: topic `{t}` is used in code but not registered in docs/messaging/kafka-topics.md")
    fail = 1
for t in sorted(registered - in_code):
    print(f"::warning:: topic `{t}` is in the catalog but referenced nowhere in code (stale row, or produced via config)")
sys.exit(fail)
